name: Build and deploy Docker image to Cloud Run
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build and push Docker image to Cloud Run
      env:
        PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        SERVICE_NAME: usdt-comparator
        IMAGE: gcr.io/$PROJECT_ID/$SERVICE_NAME
      run: |
        echo ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }} | base64 --decode > key.json
        gcloud auth activate-service-account --key-file=key.json
        gcloud config set project $PROJECT_ID
        docker buildx build --platform linux/amd64,linux/arm64 --push -t $IMAGE .
      env:
        GCP_JSON: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}